[package]
name = "google-generative-ai-rs"
version = "0.1.3"
edition = "2021"
authors = ["Mick Clarke <avastmick@outlook.com>"]
license = "MIT"
description = "An unofficial rust-based client library to interact with the Google Gemini generative AI API"
repository = "https://github.com/avastmick/google-generative-ai-rs"
readme = "README.md"
keywords = ["google", "generative", "ai", "gemini", "client"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.30" }
gcp_auth = { version = "0.10.0" }
reqwest = { version = "0.11.23", features = ["json"] }
reqwest-streams = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = {version = "1.0.108"}
tokio = { version = "1.35.1", features = ["full"] }
